TECH-862 update logo
Our-Revolution/sanctuary-cities pull request #3
Opened 2018-03-31 01:26 UTC by ericbroder

2018-03-31 01:28 UTC, ericbroder commented
ready for review but dont merge/deploy yet

2018-04-02 16:34 UTC, cjmabry requested changes
Need to regenerate css in `dist/css` but otherwise good.

2018-04-02 20:19 UTC, ericbroder commented
@cjmabry is this correct?

2018-04-02 20:41 UTC, cjmabry approved these changes

2018-04-03 19:34 UTC, merged